# Generated by Django 4.0.1 on 2022-01-06 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='gender',
            new_name='level',
        ),
    ]
