# Generated by Django 4.0.1 on 2022-01-06 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_gender_subject_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
